### ISSUE TITLE
As a Craft developer, I want comments added for all methods that can't be easily understood by all team members so that the code is easier for the team to modify.

### ISSUE THREAD

**Issue by rhartlage10** [rhartlage10/CtrlAltElite-Craft#11]
## Tasks
- [ ] Link 1 - create issue for Ronni's files
- [ ] Link 2 - create issue for Mad's files
- [ ] Link 3 - create issue for Ben's files

Time spent on this task and what files are done being modified to complete this User Story:
Ronni - 0 hours - files modified N/A
Mad - 0 hours - files modified N/A
Ben - 0 hours - files modified N/A

How to do the lists : 
https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists
Markdown :
https://www.markdownguide.org/basic-syntax/
