### ISSUE TITLE
As a Craft developer, I want more descriptive variable/function names for the code so it's clear to team members what the variables/functions do.

### ISSUE THREAD

**Issue by rhartlage10** [rhartlage10/CtrlAltElite-Craft#12]
## Tasks
- [ ] Link 1 - create issue for Ronni's files
- [ ] Link 2 - create issue for Mad's files
- [ ] Link 3 - create issue for Ben's files

Time spent on this task and what files are done being modified to complete this User Story:
Ronni - 0 hours - files modified N/A
Mad - 0 hours - files modified N/A
Ben - 0 hours - files modified N/A
